#!/usr/bin/env python3
"""
UX Excel Analyzer: Process structured usability test data from Excel files
and generate insights using a local LLM (Ollama).
"""

from __future__ import annotations

import json
import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd
from pydantic import BaseModel, Field

try:
    import ollama
except ImportError:
    ollama = None


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


class Insight(BaseModel):
    """A single insight extracted from the data."""

    category: str = Field(..., description="Insight category")
    finding: str = Field(..., description="What the data shows")
    evidence: str = Field(..., description="Specific data evidence")
    severity: str = Field(..., description="Low, Medium, High, Critical")
    recommendation: Optional[str] = Field(None, description="Action recommendation")


class DataAnalysisReport(BaseModel):
    """Validated report generated by the LLM."""

    summary: str = Field(..., description="Executive summary")
    key_insights: List[Insight] = Field(..., description="Key findings")
    anomalies: List[str] = Field(default_factory=list, description="Anomalies list")
    overall_score: int = Field(..., ge=1, le=10, description="Score from 1 to 10")
    analysis_timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())


SYSTEM_PROMPT_EXCEL_ANALYZER = """Voce e um pesquisador senior de UX e analista de dados.

Sua tarefa e transformar dados tabulares de testes de usabilidade, entrevistas ou pesquisas em uma analise executiva em portugues.
Responda SEMPRE em portugues do Brasil.
Retorne SOMENTE um objeto JSON valido. Nao use markdown, nao explique o schema e nao escreva texto fora do JSON.

Campos obrigatorios:
- summary: string com 3 a 5 frases, objetiva e executiva.
- key_insights: lista com 5 a 8 insights.
- anomalies: lista de strings com alertas, contradicoes ou pontos fora do padrao.
- overall_score: inteiro de 1 a 10.

Cada insight deve ter:
- category: tema curto em portugues.
- finding: descoberta clara, especifica e nao generica.
- evidence: evidencia concreta usando nome de coluna, contagem, percentual, media, valor observado ou exemplo textual dos dados.
- severity: Low, Medium, High ou Critical.
- recommendation: recomendacao detalhada, acionavel e conectada a descoberta.

Regras de qualidade:
- Baseie tudo apenas nos dados fornecidos.
- Nao invente numeros, quotes ou conclusoes sem evidencia.
- Prefira descobertas com impacto em UX: friccao, confusao, confianca, abandono, sucesso de tarefa, satisfacao, tempo, temas recorrentes e oportunidades de melhoria.
- Se houver poucas linhas, ainda extraia padroes, riscos e hipoteses claramente marcadas como baseadas na amostra.
- Evite frases genericas como "revisar os dados"; diga exatamente o que revisar e por que.

Formato esperado:
{
  "summary": "Resumo executivo em portugues...",
  "key_insights": [
    {
      "category": "Tema",
      "finding": "Descoberta especifica.",
      "evidence": "Evidencia concreta dos dados.",
      "severity": "High",
      "recommendation": "Recomendacao detalhada e acionavel."
    }
  ],
  "anomalies": ["Alerta ou contradicao observada."],
  "overall_score": 6
}"""


class UXExcelAnalyzer:
    """Engine for analyzing structured UX data from Excel using local LLM."""

    def __init__(self, model_name: str = "qwen3:4b", ollama_host: str = "http://localhost:11434"):
        self.model_name = model_name
        self.ollama_host = ollama_host
        self.client = None

        if ollama is None:
            logger.warning("Ollama not installed. Install with: pip install ollama")
            return

        try:
            self.client = ollama.Client(host=ollama_host)
            logger.info("Connected to Ollama at %s", ollama_host)
        except Exception as exc:
            logger.error("Failed to connect to Ollama: %s", exc)

    def load_excel(self, filepath: str, sheet_name: int | str = 0) -> pd.DataFrame:
        """Load and minimally clean an Excel sheet."""
        logger.info("Loading data from %s", filepath)
        df = pd.read_excel(filepath, sheet_name=sheet_name)
        df = df.dropna(how="all")
        df = df.dropna(axis=1, how="all")
        logger.info("Loaded %s rows and %s columns", len(df), len(df.columns))
        return df

    def _prepare_data_for_llm(
        self,
        df: pd.DataFrame,
        max_rows: int = 100,
        max_cell_chars: int = 200,
        max_columns: int = 12,
        max_prompt_chars: int = 12000,
    ) -> str:
        """Build compact context with summary stats and markdown table.

        Long text cells are truncated to *max_cell_chars* to keep the prompt
        within the model context window, which is critical for qualitative
        interview spreadsheets.
        """
        df = self._sanitize_for_analysis(df)

        summary_stats: List[str] = [
            "--- DATA SUMMARY STATISTICS ---",
            f"Total Records: {len(df)}",
            f"Columns: {', '.join(df.columns[:30])}",
        ]

        numeric_cols = df.select_dtypes(include=[np.number]).columns
        if len(numeric_cols) > 0:
            summary_stats.append("\nNumeric Metrics Averages:")
            for col in numeric_cols:
                summary_stats.append(
                    f"- {col}: Mean={df[col].mean():.2f}, Min={df[col].min()}, Max={df[col].max()}"
                )

        cat_cols = df.select_dtypes(include=["object", "category", "bool"]).columns
        if len(cat_cols) > 0:
            summary_stats.append("\nCategorical Distributions:")
            for col in cat_cols:
                if df[col].nunique(dropna=True) <= 10:
                    counts = df[col].value_counts(normalize=True, dropna=True) * 100
                    dist_str = ", ".join([f"{k}: {v:.1f}%" for k, v in counts.head(10).items()])
                    summary_stats.append(f"- {col}: {dist_str}")

        raw_data: List[str] = ["\n--- RAW DATA SAMPLE ---"]
        sample_df = df.head(max_rows) if len(df) > max_rows else df.copy()
        if len(df) > max_rows:
            raw_data.append(f"(Showing first {max_rows} rows out of {len(df)})")

        if len(sample_df.columns) > max_columns:
            kept_cols = sample_df.columns[:max_columns].tolist()
            raw_data.append(
                f"(Showing first {max_columns} columns out of {len(df.columns)} to preserve context window)"
            )
            raw_data.append("\n--- COMPACT FIELD COVERAGE FOR OMITTED COLUMNS ---")
            omitted_cols = sample_df.columns[max_columns:].tolist()
            for col in omitted_cols[:30]:
                values = df[col].dropna().astype(str).map(str.strip)
                values = values[~values.str.lower().isin({"", "nan", "none", "null", "n/a", "na"})]
                examples = [
                    (value[:90] + "...") if len(value) > 90 else value
                    for value in values.head(2).tolist()
                ]
                example_text = " | ".join(examples) if examples else "No valid responses"
                raw_data.append(f"- {col}: {len(values)} responses. Examples: {example_text}")
            if len(omitted_cols) > 30:
                raw_data.append(f"- ... {len(omitted_cols) - 30} additional columns omitted from compact coverage.")
            sample_df = sample_df[kept_cols].copy()

        for col in sample_df.columns:
            if sample_df[col].dtype == object:
                sample_df[col] = sample_df[col].apply(
                    lambda v: (str(v)[:max_cell_chars] + "...") if pd.notna(v) and len(str(v)) > max_cell_chars else v
                )
                sample_df[col] = sample_df[col].fillna("")

        raw_data.append(sample_df.to_csv(index=False))
        payload = "\n".join(summary_stats) + "\n" + "\n".join(raw_data)
        if len(payload) > max_prompt_chars:
            payload = payload[:max_prompt_chars] + "\n\n[TRUNCATED TO FIT CONTEXT WINDOW]"
        return payload

    @staticmethod
    def _sanitize_for_analysis(df: pd.DataFrame) -> pd.DataFrame:
        cleaned = df.copy()
        null_tokens = {"", "nan", "none", "null", "n/a", "na"}

        object_cols = cleaned.select_dtypes(include=["object", "string"]).columns
        for col in object_cols:
            cleaned[col] = cleaned[col].apply(lambda v: str(v).strip() if pd.notna(v) else v)
            cleaned[col] = cleaned[col].apply(
                lambda v: pd.NA
                if pd.notna(v) and str(v).strip().lower() in null_tokens
                else v
            )

        cleaned = cleaned.dropna(axis=0, how="all")
        cleaned = cleaned.dropna(axis=1, how="all")
        return cleaned

    @staticmethod
    def _get_response_text(response: Any) -> str:
        """Read Ollama responses across dict-like and typed client versions."""
        if isinstance(response, dict):
            return str(response.get("response", "")).strip()
        return str(getattr(response, "response", "")).strip()

    @staticmethod
    def _strip_response_noise(text: str) -> str:
        text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL | re.IGNORECASE)
        text = re.sub(r"```(?:json)?\s*", "", text, flags=re.IGNORECASE)
        return text.replace("```", "").strip()

    @staticmethod
    def _extract_json_object(text: str) -> Dict[str, Any]:
        """Extract the first balanced JSON object from a possibly noisy LLM response."""
        cleaned = UXExcelAnalyzer._strip_response_noise(text)
        if not cleaned:
            raise ValueError("A LLM retornou uma resposta vazia.")

        start = cleaned.find("{")
        if start == -1:
            raise ValueError(f"A resposta da LLM nao contem JSON: {cleaned[:180]}")

        depth = 0
        in_string = False
        escaped = False
        for idx, char in enumerate(cleaned[start:], start=start):
            if escaped:
                escaped = False
                continue
            if char == "\\":
                escaped = True
                continue
            if char == '"':
                in_string = not in_string
                continue
            if in_string:
                continue
            if char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
                if depth == 0:
                    return json.loads(cleaned[start : idx + 1])

        raise ValueError(f"A resposta da LLM contem JSON incompleto: {cleaned[:180]}")

    @staticmethod
    def _build_data_observations(df: pd.DataFrame) -> str:
        """Create deterministic signals to anchor the LLM in real evidence."""
        rows, cols = len(df), len(df.columns)
        lines: List[str] = [
            "--- OBSERVACOES DETERMINISTICAS PARA USAR COMO EVIDENCIA ---",
            f"- Amostra analisada: {rows} linhas e {cols} colunas.",
        ]

        if rows and cols:
            missing_pct = df.isna().sum().sum() / (rows * cols) * 100
            lines.append(f"- Dados ausentes no total: {missing_pct:.1f}%.")

        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        for col in numeric_cols[:8]:
            values = df[col].dropna()
            if values.empty:
                continue
            lines.append(
                f"- Coluna numerica '{col}': media={values.mean():.2f}, mediana={values.median():.2f}, "
                f"min={values.min()}, max={values.max()}."
            )

        text_cols = df.select_dtypes(include=["object", "string", "category", "bool"]).columns.tolist()
        for col in text_cols[:14]:
            values = df[col].dropna().astype(str).map(str.strip)
            values = values[~values.str.lower().isin({"", "nan", "none", "null", "n/a", "na"})]
            if values.empty:
                continue
            counts = values.value_counts()
            if counts.size <= 15:
                top = ", ".join(
                    f"{str(label)[:70]}={int(count)} ({count / len(values) * 100:.1f}%)"
                    for label, count in counts.head(5).items()
                )
                lines.append(f"- Distribuicao em '{col}' ({len(values)} respostas validas): {top}.")
            else:
                examples = " | ".join(values.head(3).map(lambda item: item[:140]).tolist())
                lines.append(f"- Campo aberto '{col}' tem {len(values)} respostas. Exemplos: {examples}.")

        return "\n".join(lines)

    def analyze_data(self, df: pd.DataFrame, context_info: str = "") -> Optional[DataAnalysisReport]:
        """Analyze DataFrame with local LLM and validate with Pydantic."""
        if not self.client:
            logger.error("Ollama client not initialized.")
            return None

        clean_df = self._sanitize_for_analysis(df)
        long_text_cols = 0
        for col in clean_df.select_dtypes(include=["object", "string"]).columns:
            avg_len = clean_df[col].dropna().astype(str).str.len().mean() if len(clean_df[col].dropna()) > 0 else 0
            if avg_len and avg_len > 80:
                long_text_cols += 1

        is_qualitative = long_text_cols > 3 or len(clean_df.columns) > 15
        max_rows = 8 if is_qualitative else 60
        max_columns = 10 if is_qualitative else 20
        data_str = self._prepare_data_for_llm(
            clean_df,
            max_rows=max_rows,
            max_cell_chars=120,
            max_columns=max_columns,
            max_prompt_chars=10000 if is_qualitative else 14000,
        )
        observations = self._build_data_observations(clean_df)
        user_message = f"""Analise os dados abaixo como um pesquisador senior de UX.

Contexto informado pelo usuario: {context_info if context_info else "Analise geral de UX/usabilidade"}

{observations}

--- DADOS PARA ANALISE ---
{data_str}

Objetivo:
- Gere uma analise rica em portugues, com 5 a 8 insights.
- Cada insight deve ter descoberta, evidencia concreta e recomendacao detalhada.
- Use os nomes das colunas, percentuais, contagens, medias e exemplos textuais quando existirem.
- Evite insight generico. Se uma evidencia for fraca por amostra pequena, diga isso na propria descoberta ou recomendacao.
- Retorne SOMENTE o JSON final."""

        attempt_prompts = [user_message]
        retry_message = (
            user_message
            + "\n\nA resposta anterior foi invalida. Retorne SOMENTE um JSON valido, em portugues, com as chaves: "
            "summary (string), key_insights (lista com 5 a 8 objetos), anomalies (lista de strings), overall_score (inteiro 1-10). "
            "Nao use markdown, nao use schema, nao explique o raciocinio."
        )
        attempt_prompts.append(retry_message)

        last_error: Optional[Exception] = None
        for attempt, prompt in enumerate(attempt_prompts, start=1):
            try:
                logger.info("Sending data to LLM for analysis (attempt %s)...", attempt)
                response: Dict[str, Any] = self.client.generate(
                    model=self.model_name,
                    prompt=prompt,
                    system=SYSTEM_PROMPT_EXCEL_ANALYZER,
                    stream=False,
                    format="json",
                    options={
                        "temperature": 0.1 if attempt == 1 else 0.0,
                        "top_p": 0.8,
                        "num_ctx": 8192,
                        "num_predict": 2600,
                    },
                )
                response_text = self._get_response_text(response)
                json_data = self._extract_json_object(response_text)
                json_data = self._normalize_llm_output(json_data)
                report = DataAnalysisReport(**json_data)
                logger.info("Analysis report generated successfully")
                return report
            except Exception as exc:
                last_error = exc
                logger.warning("Attempt %s failed: %s", attempt, exc)

        logger.error("Analysis failed after retries: %s", last_error)
        return self._build_fallback_report(clean_df, context_info, last_error)

    @staticmethod
    def _normalize_llm_output(data: Dict[str, Any]) -> Dict[str, Any]:
        """Fix common LLM output deviations before Pydantic validation."""
        if isinstance(data.get("summary"), dict):
            data["summary"] = json.dumps(data["summary"], ensure_ascii=False)

        if isinstance(data.get("key_insights"), dict):
            data["key_insights"] = [data["key_insights"]]

        if isinstance(data.get("key_insights"), list):
            data["key_insights"] = [
                insight for insight in data["key_insights"] if isinstance(insight, dict)
            ]
            for insight in data["key_insights"]:
                if isinstance(insight, dict):
                    # Common alternative output from local models.
                    if "insight" in insight and "finding" not in insight:
                        insight["finding"] = str(insight.get("insight"))
                    if "source" in insight and "evidence" not in insight:
                        insight["evidence"] = f"Source: {insight.get('source')}"
                    if "category" not in insight:
                        insight["category"] = "General"
                    if "severity" not in insight:
                        insight["severity"] = "Medium"
                    if "recommendation" not in insight:
                        insight["recommendation"] = "Investigar este ponto com a equipe de UX e priorizar melhorias no fluxo afetado."
                    for field in ("category", "finding", "evidence", "severity", "recommendation"):
                        if isinstance(insight.get(field), dict):
                            insight[field] = json.dumps(insight[field], ensure_ascii=False)
                        elif insight.get(field) is None:
                            insight[field] = ""
                        else:
                            insight[field] = str(insight[field]).strip()
                    severity = insight.get("severity", "").lower()
                    severity_map = {
                        "low": "Low",
                        "baixo": "Low",
                        "baixa": "Low",
                        "medium": "Medium",
                        "moderate": "Medium",
                        "medio": "Medium",
                        "media": "Medium",
                        "médio": "Medium",
                        "média": "Medium",
                        "high": "High",
                        "alto": "High",
                        "alta": "High",
                        "critical": "Critical",
                        "critico": "Critical",
                        "critica": "Critical",
                        "crítico": "Critical",
                        "crítica": "Critical",
                    }
                    insight["severity"] = severity_map.get(severity, "Medium")

        if isinstance(data.get("anomalies"), str):
            data["anomalies"] = [data["anomalies"]]
        elif not isinstance(data.get("anomalies"), list):
            data["anomalies"] = []
        else:
            data["anomalies"] = [str(item).strip() for item in data["anomalies"] if item is not None]

        score = data.get("overall_score")
        if isinstance(score, str):
            match = re.search(r"(\d+)", score)
            data["overall_score"] = int(match.group(1)) if match else 5
        if isinstance(score, float):
            data["overall_score"] = int(round(score))
        if data.get("overall_score") is None:
            data["overall_score"] = 5
        try:
            data["overall_score"] = max(1, min(10, int(data["overall_score"])))
        except (TypeError, ValueError):
            data["overall_score"] = 5
        if not data.get("key_insights"):
            data["key_insights"] = [
                {
                    "category": "Qualidade da resposta",
                    "finding": "O modelo nao retornou insights estruturados no formato esperado.",
                    "evidence": "A validacao local precisou completar a resposta da IA.",
                    "severity": "Medium",
                    "recommendation": "Tentar novamente com um contexto mais especifico ou uma amostra mais compacta.",
                }
            ]
        if "summary" not in data or not isinstance(data.get("summary"), str):
            data["summary"] = "A analise foi normalizada automaticamente porque a resposta da IA veio incompleta."

        return data

    @staticmethod
    def _build_fallback_report(
        df: pd.DataFrame,
        context_info: str,
        error: Optional[Exception] = None,
    ) -> DataAnalysisReport:
        """Create a useful Portuguese report when LLM output is invalid."""
        rows, cols = len(df), len(df.columns)
        missing_pct = float(df.isna().sum().sum() / (rows * cols) * 100) if rows and cols else 0.0
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        text_cols = df.select_dtypes(include=["object", "string", "category", "bool"]).columns.tolist()
        insights: List[Insight] = []

        status_cols = [
            col for col in text_cols
            if any(token in col.lower() for token in ("status", "resultado", "conclusao", "conclusão", "sucesso"))
        ]
        task_cols = [
            col for col in text_cols
            if any(token in col.lower() for token in ("tarefa", "task", "etapa", "fluxo"))
        ]

        for status_col in status_cols[:2]:
            values = df[status_col].dropna().astype(str).map(str.strip)
            lower_values = values.str.lower()
            difficulty_mask = lower_values.str.contains("dificuldade|nao realizado|não realizado|falha|erro|abandon", regex=True)
            difficulty_count = int(difficulty_mask.sum())
            if difficulty_count:
                pct = difficulty_count / len(values) * 100 if len(values) else 0
                evidence = f"{difficulty_count} de {len(values)} registros em '{status_col}' indicam dificuldade, falha ou abandono ({pct:.1f}%)."
                if task_cols:
                    task_col = task_cols[0]
                    affected_tasks = (
                        df.loc[difficulty_mask.reindex(df.index, fill_value=False), task_col]
                        .dropna()
                        .astype(str)
                        .value_counts()
                        .head(3)
                    )
                    if not affected_tasks.empty:
                        evidence += " Tarefas mais afetadas: " + ", ".join(
                            f"{task}={count}" for task, count in affected_tasks.items()
                        ) + "."
                insights.append(
                    Insight(
                        category="Friccao de tarefa",
                        finding="Ha um volume relevante de execucoes com dificuldade, falha ou abandono.",
                        evidence=evidence,
                        severity="High" if pct >= 35 else "Medium",
                        recommendation=(
                            "Priorizar a revisao das tarefas mais afetadas, observar gravacoes ou comentarios dessas sessoes "
                            "e redesenhar os pontos onde o usuario perde orientacao, nao encontra a acao ou precisa de ajuda."
                        ),
                    )
                )

        if numeric_cols:
            metrics = []
            for col in numeric_cols:
                values = df[col].dropna()
                if not values.empty:
                    metrics.append((col, float(values.mean()), values.min(), values.max(), float(values.median())))
            for col, mean, min_value, max_value, median in sorted(metrics, key=lambda item: item[1])[:3]:
                insights.append(
                    Insight(
                        category="Metrica quantitativa",
                        finding=f"A coluna '{col}' merece atencao por apresentar media de {mean:.2f}.",
                        evidence=f"{col}: media={mean:.2f}, mediana={median:.2f}, minimo={min_value}, maximo={max_value}.",
                        severity="High" if mean <= 3 else "Medium",
                        recommendation=(
                            f"Filtrar os registros mais criticos de '{col}' e cruzar com comentarios abertos "
                            "para entender se o problema vem de clareza, tempo, confianca ou dificuldade operacional."
                        ),
                    )
                )

        for col in text_cols[:14]:
            normalized_col = col.lower()
            if any(token in normalized_col for token in ("participante", "participant", "respondente", "nome", "email", "id")):
                continue
            values = df[col].dropna().astype(str).map(str.strip)
            values = values[~values.str.lower().isin({"", "nan", "none", "null", "n/a", "na"})]
            if values.empty:
                continue
            counts = values.value_counts()
            top_value = str(counts.index[0])
            top_count = int(counts.iloc[0])
            pct = top_count / len(values) * 100
            unique_ratio = counts.size / len(values)
            if counts.size <= 15 and top_count >= 2:
                insights.append(
                    Insight(
                        category="Padrao recorrente",
                        finding=f"'{top_value}' e o valor mais frequente em '{col}'.",
                        evidence=f"{top_count} de {len(values)} respostas validas em '{col}' ({pct:.1f}%).",
                        severity="High" if pct >= 60 else "Medium",
                        recommendation=(
                            f"Usar '{col}' como segmento de analise e comparar esse grupo com os demais para entender "
                            "se o padrao representa sucesso, friccao ou uma necessidade especifica."
                        ),
                    )
                )
            elif unique_ratio >= 0.75 or values.str.len().mean() > 35:
                examples = " | ".join(values.head(2).map(lambda item: item[:120]).tolist())
                insights.append(
                    Insight(
                        category="Feedback aberto",
                        finding=f"O campo aberto '{col}' concentra material qualitativo para extrair causas de friccao.",
                        evidence=f"{len(values)} respostas validas. Exemplos: {examples}.",
                        severity="Medium",
                        recommendation=(
                            f"Codificar manualmente as respostas de '{col}' em temas como clareza, confianca, tempo, erro "
                            "e expectativa para priorizar melhorias com base em recorrencia."
                        ),
                    )
                )
            else:
                continue
            if len(insights) >= 6:
                break

        if missing_pct > 10:
            insights.append(
                Insight(
                    category="Completude dos dados",
                    finding="Ha dados ausentes suficientes para afetar a leitura de alguns padroes.",
                    evidence=f"Percentual total de campos ausentes: {missing_pct:.1f}% em {rows} linhas e {cols} colunas.",
                    severity="Medium" if missing_pct < 30 else "High",
                    recommendation=(
                        "Antes de tomar decisao final, verificar quais perguntas ou participantes concentram os vazios "
                        "e separar ausencia real de resposta nao aplicavel."
                    ),
                )
            )

        insights.append(
            Insight(
                category="Confiabilidade da IA",
                finding="A IA local nao retornou JSON valido, entao esta analise foi montada por regras locais sobre os dados.",
                evidence=f"Erro tecnico: {str(error)[:160] if error else 'resposta invalida da LLM'}.",
                severity="Low",
                recommendation=(
                    "Reexecutar a analise apos confirmar que o modelo qwen3:4b esta carregado; use esta versao como "
                    "triagem inicial e valide os pontos criticos na aba de visualizacoes."
                ),
            )
        )

        while len(insights) < 5:
            insights.append(
                Insight(
                    category="Perfil do dataset",
                    finding="A base combina sinais estruturados e respostas textuais que devem ser analisados em conjunto.",
                    evidence=f"Foram detectadas {len(numeric_cols)} colunas numericas e {len(text_cols)} colunas textuais/categoricas.",
                    severity="Low",
                    recommendation=(
                        "Cruzar metricas numericas com comentarios para transformar sintomas quantitativos em causas de UX."
                    ),
                )
            )
        insights = insights[:8]

        summary = (
            f"A analise identificou {rows} registros e {cols} colunas, com {missing_pct:.1f}% de campos ausentes. "
            f"Como a resposta da IA local veio invalida, os insights abaixo foram gerados por uma camada local de "
            f"analise descritiva. Contexto considerado: {context_info or 'analise geral de UX/usabilidade'}."
        )
        anomalies = []
        if missing_pct > 30:
            anomalies.append(f"Alto volume de dados ausentes: {missing_pct:.1f}%.")
        if error:
            anomalies.append(f"Erro tecnico da LLM: {str(error)[:180]}")

        return DataAnalysisReport(
            summary=summary,
            key_insights=insights,
            anomalies=anomalies,
            overall_score=5,
        )

    def export_report(self, report: DataAnalysisReport, filepath: str) -> None:
        """Export analysis report to markdown."""
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("# UX Data Analysis Report\n\n")
            f.write(f"*Generated on: {report.analysis_timestamp}*\n\n")
            f.write("## Executive Summary\n")
            f.write(f"{report.summary}\n\n")
            f.write(f"**Overall Usability Score:** {report.overall_score}/10\n\n")
            f.write("## Key Insights\n\n")

            for i, insight in enumerate(report.key_insights, 1):
                f.write(f"### {i}. {insight.category}\n")
                f.write(f"- **Finding:** {insight.finding}\n")
                f.write(f"- **Evidence:** {insight.evidence}\n")
                f.write(f"- **Severity:** {insight.severity}\n")
                if insight.recommendation:
                    f.write(f"- **Recommendation:** {insight.recommendation}\n")
                f.write("\n")

            if report.anomalies:
                f.write("## Anomalies and Outliers\n\n")
                for anomaly in report.anomalies:
                    f.write(f"- {anomaly}\n")

        logger.info("Report exported to %s", filepath)


def create_sample_excel(filepath: str) -> pd.DataFrame:
    """Create simple sample Excel file for local testing."""
    data = {
        "Session_ID": [f"S{i:03d}" for i in range(1, 21)],
        "Task_Name": ["Login"] * 10 + ["Checkout"] * 10,
        "Success": [
            True,
            True,
            False,
            True,
            True,
            True,
            False,
            True,
            True,
            True,
            True,
            False,
            False,
            True,
            False,
            True,
            True,
            False,
            True,
            True,
        ],
        "Completion_Time_Sec": [
            45,
            50,
            120,
            40,
            55,
            48,
            180,
            42,
            51,
            47,
            180,
            350,
            420,
            195,
            380,
            170,
            210,
            400,
            185,
            190,
        ],
        "Error_Count": [0, 0, 2, 0, 1, 0, 3, 0, 0, 0, 1, 4, 5, 1, 4, 0, 2, 3, 1, 0],
        "Satisfaction_Rating": [5, 4, 2, 5, 4, 5, 1, 5, 4, 5, 4, 1, 1, 3, 2, 4, 3, 1, 4, 4],
        "User_Age": [25, 34, 55, 28, 42, 31, 62, 24, 38, 29, 25, 55, 62, 34, 42, 28, 31, 38, 24, 29],
        "Experience_Level": [
            "Expert",
            "Intermediate",
            "Novice",
            "Expert",
            "Intermediate",
            "Expert",
            "Novice",
            "Expert",
            "Intermediate",
            "Expert",
            "Expert",
            "Novice",
            "Novice",
            "Intermediate",
            "Intermediate",
            "Expert",
            "Expert",
            "Intermediate",
            "Expert",
            "Expert",
        ],
    }
    df = pd.DataFrame(data)
    df.to_excel(filepath, index=False)
    logger.info("Created sample Excel file at %s", filepath)
    return df


def main() -> None:
    base_dir = Path(__file__).resolve().parent
    excel_path = str(base_dir / "sample_ux_data.xlsx")
    create_sample_excel(excel_path)

    analyzer = UXExcelAnalyzer(model_name="qwen3:4b")
    df = analyzer.load_excel(excel_path)
    report = analyzer.analyze_data(
        df,
        context_info="A/B test comparing new Login and Checkout flows.",
    )

    if report:
        report_path = str(base_dir / "ux_analysis_report.md")
        analyzer.export_report(report, report_path)
        print(f"OVERALL SCORE: {report.overall_score}/10")
        print(report.summary)
    else:
        print("Analysis failed. Check Ollama connection.")


if __name__ == "__main__":
    main()
