#!/usr/bin/env python3
"""
UX Excel Analyzer: Process structured usability test data from Excel files
and generate insights using a local LLM (Ollama).
"""

from __future__ import annotations

import json
import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd
from pydantic import BaseModel, Field

try:
    import ollama
except ImportError:
    ollama = None


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


class Insight(BaseModel):
    """A single insight extracted from the data."""

    category: str = Field(..., description="Insight category")
    finding: str = Field(..., description="What the data shows")
    evidence: str = Field(..., description="Specific data evidence")
    severity: str = Field(..., description="Low, Medium, High, Critical")
    recommendation: Optional[str] = Field(None, description="Action recommendation")


class DataAnalysisReport(BaseModel):
    """Validated report generated by the LLM."""

    summary: str = Field(..., description="Executive summary")
    key_insights: List[Insight] = Field(..., description="Key findings")
    anomalies: List[str] = Field(default_factory=list, description="Anomalies list")
    overall_score: int = Field(..., ge=1, le=10, description="Score from 1 to 10")
    analysis_timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())


SYSTEM_PROMPT_EXCEL_ANALYZER = """You are a Senior UX Researcher and Data Analyst.

YOUR TASK:
Analyze the provided tabular data from usability testing sessions, context interviews, or UX surveys
and generate a comprehensive, structured UX analysis report.
Return ONLY a valid JSON object matching the schema below.
DO NOT return the schema description. RETURN THE ACTUAL VALUES, not types.
DO NOT wrap your answer in markdown code fences.
DO NOT include chain-of-thought, explanations, or any text outside the JSON object.

LANGUAGE:
Always write the final report in Brazilian Portuguese, even when column names,
raw comments, product terms, or examples are in English.
Keep product names, feature names, and technical terms as written in the data,
but explain findings, evidence, anomalies, and recommendations in Portuguese.

REQUIRED FIELDS:
- summary: a STRING with 3-5 executive sentences. NEVER a dict or object.
- key_insights: a LIST of 5-8 insight objects.
- anomalies: a LIST of short strings describing contradictions, outliers, or unexpected patterns.
- overall_score: an INTEGER between 1 and 10 reflecting overall UX quality observed.

Each insight must be an object with these string fields:
- category
- finding
- evidence
- severity (Low, Medium, High, or Critical)
- recommendation

WHAT COUNTS AS A UX INSIGHT (focus on these):
- Satisfaction, confidence, or ease-of-use scores that are below expectations (scale columns).
- Tasks or steps where users failed, struggled, or abandoned.
- Qualitative feedback describing confusion, friction, missing information, or unmet expectations.
- Patterns in open-ended comments that reveal mental models, pain points, or workarounds.
- Gaps between user expectations and the system's actual behavior.
- Learnability issues: users who needed help, took longer, or had to retry.
- Trust or safety concerns expressed about the product.

WHAT IS NOT A UX INSIGHT (do NOT generate insights from these):
- Demographic columns (gender, age, city, job title, education).
- Metadata columns (respondent name, email, interview date, interviewer name, ID, row number).
- Administrative columns (who did the data entry, session code, form number).

QUALITY BAR:
- Each finding must explain what the pattern means for the user experience, not just describe the data.
- Each evidence field must cite the column name plus a concrete value: count, percentage, mean, scale score, or textual example.
- Each recommendation must be specific and actionable: say what to redesign, test, investigate, or prioritize.
- If the sample is small, flag it but still extract directional insights.

HALLUCINATION PREVENTION:
- Base every insight strictly on the data provided.
- Do not invent numbers, quotes, tasks, participants, or product features.
- Do not infer demographics or motivations unless directly supported by the data.

CORRECT EXAMPLE OUTPUT (copy the structure, not the content):
{
  "summary": "Os participantes relataram baixa confianca ao lidar com rotinas criticas e dificuldade em localizar acoes principais. Os sinais de friccao se concentram nas etapas de maior complexidade e nas telas com baixo feedback do sistema. A prioridade de UX deve ser aumentar a clareza das proximas etapas, adicionar confirmacoes visuais e validar os fluxos criticos com nova rodada de teste.",
  "key_insights": [
    {
      "category": "Confianca do usuario",
      "finding": "Participantes demonstram inseguranca ao executar rotinas criticas, o que pode levar a abandono ou erros nao reportados.",
      "evidence": "4 de 8 participantes mencionaram receio de automatizar rotinas core na coluna 'Comentario'; media de confianca na coluna 'Escala de confianca' foi 2.8 de 5.",
      "severity": "High",
      "recommendation": "Adicionar indicadores de risco, mensagens de confirmacao e resumo da acao antes de concluir rotinas criticas. Testar em nova rodada se esses elementos reduzem o abandono sem adicionar friccao."
    }
  ],
  "anomalies": ["Dois participantes relataram alta satisfacao mesmo apresentando dificuldades na rastreabilidade."],
  "overall_score": 6
}

CRITICAL: Return ONLY a single valid JSON object with REAL values. No markdown. No extra text.
If the data is qualitative interview text, still return the same JSON structure summarizing the main UX themes."""


class UXExcelAnalyzer:
    """Engine for analyzing structured UX data from Excel using local LLM."""

    def __init__(self, model_name: str = "qwen3:4b", ollama_host: str = "http://localhost:11434"):
        self.model_name = model_name
        self.ollama_host = ollama_host
        self.client = None

        if ollama is None:
            logger.warning("Ollama not installed. Install with: pip install ollama")
            return

        try:
            self.client = ollama.Client(host=ollama_host)
            logger.info("Connected to Ollama at %s", ollama_host)
        except Exception as exc:
            logger.error("Failed to connect to Ollama: %s", exc)

    def load_excel(self, filepath: str, sheet_name: int | str = 0) -> pd.DataFrame:
        """Load and minimally clean an Excel sheet."""
        logger.info("Loading data from %s", filepath)
        df = pd.read_excel(filepath, sheet_name=sheet_name)
        df = df.dropna(how="all")
        df = df.dropna(axis=1, how="all")
        logger.info("Loaded %s rows and %s columns", len(df), len(df.columns))
        return df

    def _prepare_data_for_llm(
        self,
        df: pd.DataFrame,
        max_rows: int = 100,
        max_cell_chars: int = 200,
        max_columns: int = 12,
        max_prompt_chars: int = 12000,
    ) -> str:
        """Build compact context with summary stats and markdown table.

        Long text cells are truncated to *max_cell_chars* to keep the prompt
        within the model context window, which is critical for qualitative
        interview spreadsheets.
        """
        df = self._sanitize_for_analysis(df)

        summary_stats: List[str] = [
            "--- DATA SUMMARY STATISTICS ---",
            f"Total Records: {len(df)}",
            f"Columns: {', '.join(df.columns[:30])}",
        ]

        numeric_cols = df.select_dtypes(include=[np.number]).columns
        if len(numeric_cols) > 0:
            summary_stats.append("\nNumeric Metrics Averages:")
            for col in numeric_cols:
                summary_stats.append(
                    f"- {col}: Mean={df[col].mean():.2f}, Min={df[col].min()}, Max={df[col].max()}"
                )

        cat_cols = df.select_dtypes(include=["object", "category", "bool"]).columns
        if len(cat_cols) > 0:
            summary_stats.append("\nCategorical Distributions:")
            for col in cat_cols:
                if df[col].nunique(dropna=True) <= 10:
                    counts = df[col].value_counts(normalize=True, dropna=True) * 100
                    dist_str = ", ".join([f"{k}: {v:.1f}%" for k, v in counts.head(10).items()])
                    summary_stats.append(f"- {col}: {dist_str}")

        raw_data: List[str] = ["\n--- RAW DATA SAMPLE ---"]
        sample_df = df.head(max_rows) if len(df) > max_rows else df.copy()
        if len(df) > max_rows:
            raw_data.append(f"(Showing first {max_rows} rows out of {len(df)})")

        if len(sample_df.columns) > max_columns:
            kept_cols = sample_df.columns[:max_columns].tolist()
            raw_data.append(
                f"(Showing first {max_columns} columns out of {len(df.columns)} to preserve context window)"
            )
            raw_data.append("\n--- COMPACT FIELD COVERAGE FOR OMITTED COLUMNS ---")
            omitted_cols = sample_df.columns[max_columns:].tolist()
            for col in omitted_cols[:30]:
                values = df[col].dropna().astype(str).map(str.strip)
                values = values[~values.str.lower().isin({"", "nan", "none", "null", "n/a", "na"})]
                examples = [
                    (value[:90] + "...") if len(value) > 90 else value
                    for value in values.head(2).tolist()
                ]
                example_text = " | ".join(examples) if examples else "No valid responses"
                raw_data.append(f"- {col}: {len(values)} responses. Examples: {example_text}")
            if len(omitted_cols) > 30:
                raw_data.append(f"- ... {len(omitted_cols) - 30} additional columns omitted from compact coverage.")
            sample_df = sample_df[kept_cols].copy()

        for col in sample_df.columns:
            if sample_df[col].dtype == object:
                sample_df[col] = sample_df[col].apply(
                    lambda v: (str(v)[:max_cell_chars] + "...") if pd.notna(v) and len(str(v)) > max_cell_chars else v
                )
                sample_df[col] = sample_df[col].fillna("")

        raw_data.append(sample_df.to_csv(index=False))
        payload = "\n".join(summary_stats) + "\n" + "\n".join(raw_data)
        if len(payload) > max_prompt_chars:
            payload = payload[:max_prompt_chars] + "\n\n[TRUNCATED TO FIT CONTEXT WINDOW]"
        return payload

    @staticmethod
    def _sanitize_for_analysis(df: pd.DataFrame) -> pd.DataFrame:
        cleaned = df.copy()
        null_tokens = {"", "nan", "none", "null", "n/a", "na"}

        object_cols = cleaned.select_dtypes(include=["object", "string"]).columns
        for col in object_cols:
            cleaned[col] = cleaned[col].apply(lambda v: str(v).strip() if pd.notna(v) else v)
            cleaned[col] = cleaned[col].apply(
                lambda v: pd.NA
                if pd.notna(v) and str(v).strip().lower() in null_tokens
                else v
            )

        cleaned = cleaned.dropna(axis=0, how="all")
        cleaned = cleaned.dropna(axis=1, how="all")
        return cleaned

    @staticmethod
    def _get_response_text(response: Any) -> str:
        """Read Ollama responses across dict-like and typed client versions.

        Qwen3 with thinking enabled puts output in 'thinking' and leaves
        'response' empty. We always pass think=False, but guard against it anyway.
        """
        if isinstance(response, dict):
            text = str(response.get("response", "") or "").strip()
            if not text:
                text = str(response.get("thinking", "") or "").strip()
            return text

        text = str(getattr(response, "response", "") or "").strip()
        if not text:
            text = str(getattr(response, "thinking", "") or "").strip()
            if text:
                logger.warning(
                    "LLM response was empty but 'thinking' field had content "
                    "(think=False may not have been respected). Falling back to thinking content."
                )
        return text

    @staticmethod
    def _strip_response_noise(text: str) -> str:
        text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL | re.IGNORECASE)
        text = re.sub(r"```(?:json)?\s*", "", text, flags=re.IGNORECASE)
        return text.replace("```", "").strip()

    @staticmethod
    def _extract_json_object(text: str) -> Dict[str, Any]:
        """Extract the first balanced JSON object from a possibly noisy LLM response."""
        cleaned = UXExcelAnalyzer._strip_response_noise(text)
        if not cleaned:
            raise ValueError("A LLM retornou uma resposta vazia.")

        start = cleaned.find("{")
        if start == -1:
            raise ValueError(f"A resposta da LLM nao contem JSON: {cleaned[:180]}")

        depth = 0
        in_string = False
        escaped = False
        for idx, char in enumerate(cleaned[start:], start=start):
            if escaped:
                escaped = False
                continue
            if char == "\\":
                escaped = True
                continue
            if char == '"':
                in_string = not in_string
                continue
            if in_string:
                continue
            if char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
                if depth == 0:
                    return json.loads(cleaned[start : idx + 1])

        raise ValueError(f"A resposta da LLM contem JSON incompleto: {cleaned[:180]}")

    # -----------------------------------------------------------------------
    # Column classification
    # -----------------------------------------------------------------------

    _DEMO_TOKENS = frozenset({
        "sexo", "genero", "gênero", "idade", "escolaridade", "estado civil",
        "estadocivil", "cidade", "bairro", "cep", "nascimento", "profissao",
        "profissão", "cargo", "formacao", "formação", "raca", "raça",
        "etnia", "estado", "regiao", "região",
    })
    _META_TOKENS = frozenset({
        "responsavel", "responsável", "tabulacao", "tabulação", "entrevistador",
        "data da entrevista", "data de coleta", "data de", "codigo", "código",
        "id", "nome", "email", "telefone", "empresa", "organização", "organizacao",
        "sessao", "sessão", "numero", "número", "timestamp", "horario", "horário",
    })
    _SCALE_TOKENS = frozenset({
        "escala", "nota", "satisfacao", "satisfação", "nps", "likert",
        "avaliacao", "avaliação", "rating", "score", "pontuacao", "pontuação",
        "confianca", "confiança", "facilidade", "clareza", "qualidade",
        "usabilidade", "utilidade", "eficiencia", "eficiência", "dificuldade",
        "1 a 5", "1 a 10", "0 a 10", "de 1 a", "de 0 a",
    })
    _TASK_TOKENS = frozenset({
        "tarefa", "task", "status", "resultado", "conclusao", "conclusão",
        "sucesso", "falha", "execucao", "execução", "tempo", "duracao",
        "duração", "tentativas", "etapa", "fluxo", "passo",
    })
    _FEEDBACK_TOKENS = frozenset({
        "comentario", "comentário", "observacao", "observação", "sugestao",
        "sugestão", "motivo", "porque", "por que", "explique", "descreva",
        "feedback", "opiniao", "opinião", "diga", "relate", "desafio",
        "dificuldade", "dificultou", "problema", "melhoria", "o que",
        "conte", "relato", "quais", "como foi", "como voce", "como você",
        "fale sobre", "experiencia", "experiência",
    })

    @classmethod
    def _classify_column(cls, col: str) -> str:
        """Return column type: 'scale', 'task', 'feedback', 'demo', 'meta', or 'other'.

        UX-signal types are checked first so that short demographic tokens like
        'idade' don't accidentally match inside words like 'necessidades'.
        """
        normalized = col.lower().strip()
        if any(token in normalized for token in cls._SCALE_TOKENS):
            return "scale"
        if any(token in normalized for token in cls._TASK_TOKENS):
            return "task"
        if any(token in normalized for token in cls._FEEDBACK_TOKENS):
            return "feedback"
        if any(token in normalized for token in cls._DEMO_TOKENS):
            return "demo"
        if any(token in normalized for token in cls._META_TOKENS):
            return "meta"
        return "other"

    @classmethod
    def _split_columns_by_type(cls, df: pd.DataFrame) -> Dict[str, List[str]]:
        buckets: Dict[str, List[str]] = {
            "demo": [], "meta": [], "scale": [], "task": [], "feedback": [], "other": []
        }
        for col in df.columns:
            buckets[cls._classify_column(col)].append(col)
        return buckets

    # -----------------------------------------------------------------------
    # Deterministic observations for LLM anchoring
    # -----------------------------------------------------------------------

    @classmethod
    def _build_data_observations(cls, df: pd.DataFrame) -> str:
        """Create UX-focused deterministic signals to anchor the LLM in real evidence."""
        rows, cols_n = len(df), len(df.columns)
        lines: List[str] = [
            "--- UX-RELEVANT OBSERVATIONS (use as evidence anchors) ---",
            f"- Sample: {rows} records, {cols_n} columns.",
        ]
        if rows and cols_n:
            missing_pct = df.isna().sum().sum() / (rows * cols_n) * 100
            lines.append(f"- Overall missing data: {missing_pct:.1f}%.")

        buckets = cls._split_columns_by_type(df)

        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        ux_numeric = [
            col for col in numeric_cols
            if cls._classify_column(col) not in ("demo", "meta")
        ]
        if ux_numeric:
            lines.append("- UX numeric signals:")
            for col in ux_numeric[:10]:
                values = df[col].dropna()
                if values.empty:
                    continue
                col_type = cls._classify_column(col)
                hint = " [escala de avaliacao]" if col_type == "scale" else ""
                lines.append(
                    f"  * '{col}'{hint}: mean={values.mean():.2f}, median={values.median():.2f}, "
                    f"min={values.min()}, max={values.max()}."
                )

        for bucket_key, label in (
            ("task", "Task/status columns"),
            ("scale", "Evaluation scale columns"),
            ("feedback", "Open feedback columns"),
            ("other", "Other columns"),
        ):
            for col in buckets[bucket_key][:10]:
                values = df[col].dropna().astype(str).map(str.strip)
                values = values[~values.str.lower().isin({"", "nan", "none", "null", "n/a", "na"})]
                if values.empty:
                    continue
                counts = values.value_counts()
                if counts.size <= 15:
                    top = ", ".join(
                        f"{str(lbl)[:70]}={int(cnt)} ({cnt / len(values) * 100:.1f}%)"
                        for lbl, cnt in counts.head(5).items()
                    )
                    lines.append(f"- [{label}] '{col}' ({len(values)} valid): {top}.")
                else:
                    examples = " | ".join(values.head(3).map(lambda item: item[:130]).tolist())
                    lines.append(f"- [{label}] '{col}': {len(values)} open responses. Examples: {examples}.")

        if buckets["demo"] or buckets["meta"]:
            lines.append(
                "- CONTEXT ONLY (do NOT generate UX insights from these): "
                + ", ".join(f"'{c}'" for c in buckets["demo"] + buckets["meta"])
                + "."
            )

        return "\n".join(lines)

    def analyze_data(self, df: pd.DataFrame, context_info: str = "") -> Optional[DataAnalysisReport]:
        """Analyze DataFrame with local LLM and validate with Pydantic."""
        if not self.client:
            logger.error("Ollama client not initialized.")
            return None

        clean_df = self._sanitize_for_analysis(df)
        long_text_cols = 0
        for col in clean_df.select_dtypes(include=["object", "string"]).columns:
            avg_len = clean_df[col].dropna().astype(str).str.len().mean() if len(clean_df[col].dropna()) > 0 else 0
            if avg_len and avg_len > 80:
                long_text_cols += 1

        is_qualitative = long_text_cols > 3 or len(clean_df.columns) > 15
        max_rows = 8 if is_qualitative else 60
        max_columns = 10 if is_qualitative else 20
        data_str = self._prepare_data_for_llm(
            clean_df,
            max_rows=max_rows,
            max_cell_chars=120,
            max_columns=max_columns,
            max_prompt_chars=10000 if is_qualitative else 14000,
        )
        observations = self._build_data_observations(clean_df)
        buckets = self._split_columns_by_type(clean_df)
        demo_meta_note = ""
        skip_cols = buckets["demo"] + buckets["meta"]
        if skip_cols:
            demo_meta_note = (
                "\n\nCOLUNAS DEMOGRAFICAS / METADADOS (use apenas como contexto, NAO gere insights a partir delas):\n"
                + ", ".join(f"'{c}'" for c in skip_cols)
            )
        ux_cols = buckets["scale"] + buckets["task"] + buckets["feedback"] + buckets["other"]
        ux_note = ""
        if ux_cols:
            ux_note = (
                "\n\nCOLUNAS DE UX RELEVANTES (foque os insights nestas):\n"
                + ", ".join(f"'{c}'" for c in ux_cols[:20])
            )

        user_message = f"""Analyze the following usability/UX data as a Senior UX Researcher.

User-provided context: {context_info if context_info else "General UX/usability analysis"}
{demo_meta_note}{ux_note}

{observations}

--- DATA ---
{data_str}

Instructions:
- Generate the full report in Brazilian Portuguese.
- Each insight must have a clear finding about the user experience, concrete evidence from the data, and a detailed actionable recommendation.
- Use column names, percentages, means, and textual examples as evidence.
- Do NOT create insights about demographic or metadata columns.
- Return ONLY the final JSON object."""

        attempt_prompts = [user_message]
        retry_message = (
            user_message
            + "\n\nA resposta anterior foi invalida. Retorne SOMENTE um JSON valido, totalmente em portugues do Brasil, com as chaves: "
            "summary (string), key_insights (lista com 5 a 8 objetos), anomalies (lista de strings), overall_score (inteiro 1-10). "
            "Nao use markdown, nao use schema, nao explique o raciocinio."
        )
        attempt_prompts.append(retry_message)

        last_error: Optional[Exception] = None
        for attempt, prompt in enumerate(attempt_prompts, start=1):
            try:
                logger.info("Sending data to LLM for analysis (attempt %s)...", attempt)
                response: Dict[str, Any] = self.client.generate(
                    model=self.model_name,
                    prompt=prompt,
                    system=SYSTEM_PROMPT_EXCEL_ANALYZER,
                    stream=False,
                    think=False,
                    format="json",
                    options={
                        "temperature": 0.1 if attempt == 1 else 0.0,
                        "top_p": 0.8,
                        "num_ctx": 8192,
                        "num_predict": 2600,
                    },
                )
                response_text = self._get_response_text(response)
                json_data = self._extract_json_object(response_text)
                logger.debug(
                    "Raw LLM JSON keys=%s insights_type=%s insights_len=%s",
                    list(json_data.keys()),
                    type(json_data.get("key_insights")).__name__,
                    len(json_data.get("key_insights", [])) if isinstance(json_data.get("key_insights"), list) else "n/a",
                )
                json_data = self._normalize_llm_output(json_data)
                if not json_data.get("key_insights"):
                    raise ValueError(
                        f"LLM returned zero usable insights. Raw keys: {list(json_data.keys())}"
                    )
                report = DataAnalysisReport(**json_data)
                logger.info(
                    "Analysis report generated successfully (%d insights, score=%s)",
                    len(report.key_insights),
                    report.overall_score,
                )
                return report
            except Exception as exc:
                last_error = exc
                logger.warning("Attempt %s failed: %s", attempt, exc)

        logger.error("Analysis failed after retries: %s", last_error)
        return self._build_fallback_report(clean_df, context_info, last_error)

    @staticmethod
    def _infer_insight_category(text: str) -> str:
        lower = text.lower()
        if any(token in lower for token in ("confian", "seguran", "risco", "rollback")):
            return "Confianca do usuario"
        if any(token in lower for token in ("dificuldade", "fric", "confus", "erro", "falha", "abandon")):
            return "Friccao de uso"
        if any(token in lower for token in ("satisf", "nota", "escala", "avali")):
            return "Avaliacao de usabilidade"
        if any(token in lower for token in ("tempo", "demor", "eficien", "rapidez")):
            return "Eficiencia do fluxo"
        if any(token in lower for token in ("interface", "icone", "ícone", "tela", "visual")):
            return "Clareza da interface"
        if any(token in lower for token in ("coment", "feedback", "sugest", "entrevista")):
            return "Feedback qualitativo"
        return "Insight UX"

    @staticmethod
    def _looks_english(text: str) -> bool:
        lower = f" {text.lower()} "
        english_hits = sum(
            token in lower
            for token in (
                " the ", " users ", " user ", " data ", " shows ", " main ",
                " issues ", " struggle ", " mentioned ", " difficulty ",
                " suggested ", " section ", " screen ", " generally ",
            )
        )
        portuguese_hits = sum(
            token in lower
            for token in (
                " os ", " as ", " usuários ", " usuarios ", " dados ",
                " participantes ", " dificuldade ", " recomenda ", " análise ",
                " analise ", " experiência ", " experiencia ",
            )
        )
        return english_hits >= 2 and english_hits > portuguese_hits

    @staticmethod
    def _build_portuguese_summary_from_insights(data: Dict[str, Any]) -> str:
        insights = data.get("key_insights") or []
        count = len(insights) if isinstance(insights, list) else 0
        categories = []
        if isinstance(insights, list):
            for insight in insights[:3]:
                if isinstance(insight, dict) and insight.get("category"):
                    categories.append(str(insight["category"]))
        category_text = ", ".join(dict.fromkeys(categories)) if categories else "clareza, confianca e eficiencia"
        signal_text = "1 sinal relevante" if count == 1 else f"{count} sinais relevantes"
        return (
            f"A analise identificou {signal_text} para UX nos dados fornecidos. "
            f"Os principais temas observados envolvem {category_text}, com oportunidades de reduzir friccao, "
            "melhorar a compreensao do fluxo e apoiar decisoes de melhoria do produto. "
            "As recomendacoes devem ser priorizadas conforme impacto na jornada e recorrencia das evidencias."
        )

    @staticmethod
    def _normalize_llm_output(data: Dict[str, Any]) -> Dict[str, Any]:
        """Fix common LLM output deviations before Pydantic validation."""
        if not data.get("summary"):
            for alias in ("resumo", "executive_summary", "sintese", "síntese"):
                if data.get(alias):
                    data["summary"] = data[alias]
                    break

        if isinstance(data.get("summary"), dict):
            data["summary"] = json.dumps(data["summary"], ensure_ascii=False)

        if not data.get("key_insights"):
            for alias in ("insights", "findings", "principais_insights", "descobertas"):
                if data.get(alias):
                    data["key_insights"] = data[alias]
                    break

        if isinstance(data.get("key_insights"), dict):
            # e.g. {"insight1": {...}, "insight2": {...}} → list of values
            inner = data["key_insights"]
            if all(isinstance(v, dict) for v in inner.values()):
                data["key_insights"] = list(inner.values())
            else:
                data["key_insights"] = [inner]

        if isinstance(data.get("key_insights"), list):
            coerced = []
            for item in data["key_insights"]:
                if isinstance(item, dict):
                    coerced.append(item)
                elif isinstance(item, str) and item.strip():
                    # LLM returned a plain string — wrap it as a minimal insight dict
                    text = item.strip()
                    coerced.append({
                        "category": UXExcelAnalyzer._infer_insight_category(text),
                        "finding": text,
                        "evidence": text[:220],
                        "severity": "Medium",
                        "recommendation": "Validar este ponto com os dados detalhados e transformar em melhoria priorizada no backlog de UX.",
                    })
            data["key_insights"] = coerced
            for insight in data["key_insights"]:
                if isinstance(insight, dict):
                    # Common alternative output from local models.
                    if "insight" in insight and "finding" not in insight:
                        insight["finding"] = str(insight.get("insight"))
                    if "description" in insight and "finding" not in insight:
                        insight["finding"] = str(insight.get("description"))
                    if "descricao" in insight and "finding" not in insight:
                        insight["finding"] = str(insight.get("descricao"))
                    if "descoberta" in insight and "finding" not in insight:
                        insight["finding"] = str(insight.get("descoberta"))
                    if "source" in insight and "evidence" not in insight:
                        insight["evidence"] = f"Source: {insight.get('source')}"
                    if "evidencia" in insight and "evidence" not in insight:
                        insight["evidence"] = str(insight.get("evidencia"))
                    if "recommendation" not in insight:
                        for alias in ("recommendation", "recomendacao", "recomendação", "action", "acao", "ação"):
                            if insight.get(alias):
                                insight["recommendation"] = str(insight.get(alias))
                                break
                    if "finding" not in insight:
                        insight["finding"] = "O modelo retornou um insight sem descoberta estruturada."
                    if "category" not in insight:
                        inferred_text = str(insight.get("finding") or insight.get("description") or "")
                        insight["category"] = str(
                            insight.get("categoria")
                            or UXExcelAnalyzer._infer_insight_category(inferred_text)
                        )
                    if "evidence" not in insight:
                        insight["evidence"] = "O modelo nao estruturou a evidencia; validar contra os dados carregados."
                    if "severity" not in insight:
                        insight["severity"] = "Medium"
                    if "recommendation" not in insight:
                        insight["recommendation"] = "Investigar este ponto com a equipe de UX e priorizar melhorias no fluxo afetado."
                    for field in ("category", "finding", "evidence", "severity", "recommendation"):
                        if isinstance(insight.get(field), dict):
                            insight[field] = json.dumps(insight[field], ensure_ascii=False)
                        elif insight.get(field) is None:
                            insight[field] = ""
                        else:
                            insight[field] = str(insight[field]).strip()
                    severity = insight.get("severity", "").lower()
                    severity_map = {
                        "low": "Low",
                        "baixo": "Low",
                        "baixa": "Low",
                        "medium": "Medium",
                        "moderate": "Medium",
                        "medio": "Medium",
                        "media": "Medium",
                        "médio": "Medium",
                        "média": "Medium",
                        "high": "High",
                        "alto": "High",
                        "alta": "High",
                        "critical": "Critical",
                        "critico": "Critical",
                        "critica": "Critical",
                        "crítico": "Critical",
                        "crítica": "Critical",
                    }
                    insight["severity"] = severity_map.get(severity, "Medium")

        if isinstance(data.get("anomalies"), str):
            data["anomalies"] = [data["anomalies"]]
        elif not isinstance(data.get("anomalies"), list):
            data["anomalies"] = []
        else:
            normalized_anomalies = []
            for item in data["anomalies"]:
                if item is None:
                    continue
                if isinstance(item, dict):
                    # LLM returned {category, description} or {title, text} instead of a plain string
                    parts = []
                    for key in ("category", "title", "categoria", "titulo"):
                        if item.get(key):
                            parts.append(f"[{str(item[key]).strip()}]")
                            break
                    for key in ("description", "text", "descricao", "descricão", "finding", "detail"):
                        if item.get(key):
                            parts.append(str(item[key]).strip())
                            break
                    if not parts:
                        parts = [str(v).strip() for v in item.values() if v]
                    normalized_anomalies.append(" ".join(parts).strip())
                else:
                    normalized_anomalies.append(str(item).strip())
            data["anomalies"] = [a for a in normalized_anomalies if a]

        score = data.get("overall_score")
        if isinstance(score, str):
            match = re.search(r"(\d+)", score)
            data["overall_score"] = int(match.group(1)) if match else 5
        if isinstance(score, float):
            data["overall_score"] = int(round(score))
        if data.get("overall_score") is None:
            data["overall_score"] = 5
        try:
            data["overall_score"] = max(1, min(10, int(data["overall_score"])))
        except (TypeError, ValueError):
            data["overall_score"] = 5
        if not data.get("key_insights"):
            data["key_insights"] = []
        if "summary" not in data or not isinstance(data.get("summary"), str):
            insights = data.get("key_insights") or []
            count = len(insights) if isinstance(insights, list) else 0
            data["summary"] = (
                f"A analise identificou {count} sinais relevantes para UX a partir dos dados fornecidos. "
                "Os principais pontos indicam oportunidades de melhorar clareza, confianca e eficiencia do fluxo. "
                "As recomendacoes devem ser validadas contra as evidencias detalhadas e priorizadas conforme impacto no usuario."
            )
        elif UXExcelAnalyzer._looks_english(data["summary"]):
            logger.warning("LLM returned English summary; replacing with Portuguese summary.")
            data["summary"] = UXExcelAnalyzer._build_portuguese_summary_from_insights(data)

        return data

    @classmethod
    def _build_fallback_report(
        cls,
        df: pd.DataFrame,
        context_info: str,
        error: Optional[Exception] = None,
    ) -> DataAnalysisReport:
        """Build a UX-contextualised fallback when the LLM fails."""
        rows, cols = len(df), len(df.columns)
        missing_pct = float(df.isna().sum().sum() / (rows * cols) * 100) if rows and cols else 0.0
        buckets = cls._split_columns_by_type(df)
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        insights: List[Insight] = []

        # --- 1. Task friction (status columns) ---
        for status_col in buckets["task"][:3]:
            values = df[status_col].dropna().astype(str).map(str.strip)
            lower_values = values.str.lower()
            difficulty_mask = lower_values.str.contains(
                r"dificuldade|nao realizado|não realizado|falha|erro|abandon|nao concluiu|não concluiu",
                regex=True,
            )
            difficulty_count = int(difficulty_mask.sum())
            if not difficulty_count:
                continue
            pct = difficulty_count / len(values) * 100 if len(values) else 0
            evidence = (
                f"{difficulty_count} de {len(values)} registros em '{status_col}' "
                f"indicam dificuldade, falha ou abandono ({pct:.1f}%)."
            )
            other_task_cols = [c for c in buckets["task"] if c != status_col]
            if other_task_cols:
                task_col = other_task_cols[0]
                affected = (
                    df.loc[difficulty_mask.reindex(df.index, fill_value=False), task_col]
                    .dropna().astype(str).value_counts().head(3)
                )
                if not affected.empty:
                    evidence += " Etapas mais afetadas: " + ", ".join(
                        f"'{t}'={c}" for t, c in affected.items()
                    ) + "."
            insights.append(Insight(
                category="Friccao de tarefa",
                finding=(
                    "Ha um volume expressivo de execucoes com dificuldade, falha ou abandono, "
                    "indicando pontos criticos no fluxo do usuario."
                ),
                evidence=evidence,
                severity="High" if pct >= 35 else "Medium",
                recommendation=(
                    "Revisar as etapas com maior taxa de falha usando gravacoes de sessao ou comentarios abertos. "
                    "Identificar se o problema e de visibilidade da acao, vocabulario, fluxo ou falta de feedback "
                    "do sistema e priorizar correccoes na proxima iteracao de design."
                ),
            ))

        # --- 2. Satisfaction / scale signals ---
        ux_numeric = [
            c for c in numeric_cols
            if cls._classify_column(c) not in ("demo", "meta")
        ]
        scale_metrics = []
        for col in ux_numeric:
            values = df[col].dropna()
            if values.empty:
                continue
            scale_metrics.append((col, float(values.mean()), float(values.median()), values.min(), values.max()))
        for col, mean, median, min_v, max_v in sorted(scale_metrics, key=lambda x: x[1])[:4]:
            col_type = cls._classify_column(col)
            is_scale = col_type == "scale"
            score_max = 5.0 if max_v <= 5 else 10.0
            low_threshold = score_max * 0.5
            severity = "High" if mean <= low_threshold else "Medium"
            if is_scale:
                interpretation = (
                    f"A media de {mean:.2f} em '{col}' esta abaixo do ponto medio da escala ({score_max/2:.1f}), "
                    "sinalizando que usuarios avaliam negativamente esse aspecto da experiencia."
                    if mean <= score_max / 2
                    else f"A media de {mean:.2f} em '{col}' e moderada, com espaco relevante para melhoria."
                )
                insights.append(Insight(
                    category="Avaliacao de usabilidade",
                    finding=interpretation,
                    evidence=f"'{col}': media={mean:.2f}, mediana={median:.2f}, min={min_v}, max={max_v} (escala ate {score_max:.0f}).",
                    severity=severity,
                    recommendation=(
                        f"Investigar quais etapas ou caracteristicas do produto mais contribuem para a nota baixa em '{col}'. "
                        "Cruzar com respostas abertas para entender causas especificas e testar mudancas em nova rodada."
                    ),
                ))
            else:
                insights.append(Insight(
                    category="Metrica de desempenho",
                    finding=f"O indicador '{col}' apresenta variacao relevante que pode refletir diferenca de experiencia entre participantes.",
                    evidence=f"'{col}': media={mean:.2f}, mediana={median:.2f}, min={min_v}, max={max_v}.",
                    severity=severity,
                    recommendation=(
                        f"Segmentar os participantes pelo valor de '{col}' e comparar com outros indicadores "
                        "para identificar perfis com maior dificuldade ou menor engajamento."
                    ),
                ))
            if len(insights) >= 5:
                break

        # --- 3. Open feedback ---
        for col in buckets["feedback"][:4]:
            values = df[col].dropna().astype(str).map(str.strip)
            values = values[~values.str.lower().isin({"", "nan", "none", "null", "n/a", "na"})]
            if values.empty or len(values) < 2:
                continue
            examples = " | ".join(values.head(3).map(lambda item: item[:110]).tolist())
            insights.append(Insight(
                category="Feedback qualitativo",
                finding=(
                    f"O campo '{col}' reune respostas abertas que revelam motivacoes, dores "
                    "e expectativas dos participantes em linguagem propria."
                ),
                evidence=f"{len(values)} respostas validas em '{col}'. Exemplos: {examples}.",
                severity="Medium",
                recommendation=(
                    f"Codificar as respostas de '{col}' em temas recorrentes (clareza, confianca, tempo, erro, "
                    "expectativa, workaround) e priorizar os temas com maior frequencia no backlog de UX."
                ),
            ))
            if len(insights) >= 7:
                break

        # --- 4. Categorical task patterns (non-demo, non-meta) ---
        for col in (buckets["task"] + buckets["other"])[:8]:
            if len(insights) >= 7:
                break
            values = df[col].dropna().astype(str).map(str.strip)
            values = values[~values.str.lower().isin({"", "nan", "none", "null", "n/a", "na"})]
            if values.empty:
                continue
            counts = values.value_counts()
            if counts.size > 15 or int(counts.iloc[0]) < 2:
                continue
            top_value = str(counts.index[0])
            top_count = int(counts.iloc[0])
            pct = top_count / len(values) * 100
            if pct >= 40:
                insights.append(Insight(
                    category="Padrao comportamental",
                    finding=(
                        f"A maioria dos registros em '{col}' concentra-se em '{top_value}', "
                        "o que pode indicar um perfil ou comportamento dominante na amostra."
                    ),
                    evidence=f"{top_count} de {len(values)} respostas validas em '{col}' ({pct:.1f}%).",
                    severity="Medium",
                    recommendation=(
                        f"Investigar se o grupo '{top_value}' em '{col}' apresenta comportamentos ou dificuldades "
                        "diferentes dos demais segmentos e ajustar o design para atender melhor esse perfil."
                    ),
                ))

        # --- 5. Missing data alert ---
        if missing_pct > 10:
            insights.append(Insight(
                category="Completude dos dados",
                finding="Ha dados ausentes em volume relevante, o que pode mascarar padroes importantes.",
                evidence=f"{missing_pct:.1f}% de campos ausentes em {rows} registros e {cols} colunas.",
                severity="Medium" if missing_pct < 30 else "High",
                recommendation=(
                    "Verificar quais perguntas ou participantes concentram os campos vazios. "
                    "Separar respostas nao aplicaveis de recusas reais antes de concluir a analise."
                ),
            ))

        # --- 6. AI reliability notice (always last) ---
        insights.append(Insight(
            category="Analise gerada localmente",
            finding=(
                "A IA local nao conseguiu processar a analise, portanto os insights foram gerados "
                "por uma camada de regras descritivas sobre os dados. Os resultados sao direcionais."
            ),
            evidence=f"Erro: {str(error)[:180] if error else 'resposta invalida da LLM'}.",
            severity="Low",
            recommendation=(
                f"Reexecutar a analise apos liberar memoria RAM (o modelo {cls.__name__} precisa de ~3.7 GB livres). "
                "Enquanto isso, use esta versao como triagem e valide os pontos criticos na aba de visualizacoes."
            ),
        ))

        if len(insights) < 5:
            insights.append(Insight(
                category="Perfil da amostra",
                finding="A base combina sinais quantitativos e qualitativos que devem ser analisados em conjunto.",
                evidence=(
                    f"{len(ux_numeric)} colunas numericas de UX detectadas, "
                    f"{len(buckets['feedback'])} campos de feedback aberto, "
                    f"{len(buckets['task'])} colunas de tarefa/status."
                ),
                severity="Low",
                recommendation=(
                    "Cruzar as metricas numericas com os comentarios abertos para transformar "
                    "sintomas quantitativos em causas identificaveis e priorizaveis no backlog de UX."
                ),
            ))
        insights = list({ins.finding: ins for ins in insights}.values())[:8]

        summary = (
            f"Analise de {rows} registros e {cols} colunas com {missing_pct:.1f}% de ausencias. "
            f"Como a IA local nao retornou resposta valida, os insights foram gerados por analise descritiva automatica. "
            f"Contexto: {context_info or 'analise geral de UX/usabilidade'}. "
            f"Recomenda-se reexecutar a analise com o modelo carregado para resultados mais ricos."
        )
        anomalies = []
        if missing_pct > 30:
            anomalies.append(f"Alto volume de dados ausentes: {missing_pct:.1f}%.")
        if error:
            anomalies.append(f"Erro tecnico da LLM: {str(error)[:180]}")

        return DataAnalysisReport(
            summary=summary,
            key_insights=insights,
            anomalies=anomalies,
            overall_score=5,
        )

    def export_report(self, report: DataAnalysisReport, filepath: str) -> None:
        """Export analysis report to markdown."""
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("# UX Data Analysis Report\n\n")
            f.write(f"*Generated on: {report.analysis_timestamp}*\n\n")
            f.write("## Executive Summary\n")
            f.write(f"{report.summary}\n\n")
            f.write(f"**Overall Usability Score:** {report.overall_score}/10\n\n")
            f.write("## Key Insights\n\n")

            for i, insight in enumerate(report.key_insights, 1):
                f.write(f"### {i}. {insight.category}\n")
                f.write(f"- **Finding:** {insight.finding}\n")
                f.write(f"- **Evidence:** {insight.evidence}\n")
                f.write(f"- **Severity:** {insight.severity}\n")
                if insight.recommendation:
                    f.write(f"- **Recommendation:** {insight.recommendation}\n")
                f.write("\n")

            if report.anomalies:
                f.write("## Anomalies and Outliers\n\n")
                for anomaly in report.anomalies:
                    f.write(f"- {anomaly}\n")

        logger.info("Report exported to %s", filepath)


def create_sample_excel(filepath: str) -> pd.DataFrame:
    """Create simple sample Excel file for local testing."""
    data = {
        "Session_ID": [f"S{i:03d}" for i in range(1, 21)],
        "Task_Name": ["Login"] * 10 + ["Checkout"] * 10,
        "Success": [
            True,
            True,
            False,
            True,
            True,
            True,
            False,
            True,
            True,
            True,
            True,
            False,
            False,
            True,
            False,
            True,
            True,
            False,
            True,
            True,
        ],
        "Completion_Time_Sec": [
            45,
            50,
            120,
            40,
            55,
            48,
            180,
            42,
            51,
            47,
            180,
            350,
            420,
            195,
            380,
            170,
            210,
            400,
            185,
            190,
        ],
        "Error_Count": [0, 0, 2, 0, 1, 0, 3, 0, 0, 0, 1, 4, 5, 1, 4, 0, 2, 3, 1, 0],
        "Satisfaction_Rating": [5, 4, 2, 5, 4, 5, 1, 5, 4, 5, 4, 1, 1, 3, 2, 4, 3, 1, 4, 4],
        "User_Age": [25, 34, 55, 28, 42, 31, 62, 24, 38, 29, 25, 55, 62, 34, 42, 28, 31, 38, 24, 29],
        "Experience_Level": [
            "Expert",
            "Intermediate",
            "Novice",
            "Expert",
            "Intermediate",
            "Expert",
            "Novice",
            "Expert",
            "Intermediate",
            "Expert",
            "Expert",
            "Novice",
            "Novice",
            "Intermediate",
            "Intermediate",
            "Expert",
            "Expert",
            "Intermediate",
            "Expert",
            "Expert",
        ],
    }
    df = pd.DataFrame(data)
    df.to_excel(filepath, index=False)
    logger.info("Created sample Excel file at %s", filepath)
    return df


def main() -> None:
    base_dir = Path(__file__).resolve().parent
    excel_path = str(base_dir / "sample_ux_data.xlsx")
    create_sample_excel(excel_path)

    analyzer = UXExcelAnalyzer(model_name="qwen3:4b")
    df = analyzer.load_excel(excel_path)
    report = analyzer.analyze_data(
        df,
        context_info="A/B test comparing new Login and Checkout flows.",
    )

    if report:
        report_path = str(base_dir / "ux_analysis_report.md")
        analyzer.export_report(report, report_path)
        print(f"OVERALL SCORE: {report.overall_score}/10")
        print(report.summary)
    else:
        print("Analysis failed. Check Ollama connection.")


if __name__ == "__main__":
    main()
