#!/usr/bin/env python3
"""
UX Excel Analyzer: Process structured usability test data from Excel files
and generate insights using a local LLM (Ollama).
"""

from __future__ import annotations

import json
import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd
from pydantic import BaseModel, Field

try:
    import ollama
except ImportError:
    ollama = None


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


class Insight(BaseModel):
    """A single insight extracted from the data."""

    category: str = Field(..., description="Insight category")
    finding: str = Field(..., description="What the data shows")
    evidence: str = Field(..., description="Specific data evidence")
    severity: str = Field(..., description="Low, Medium, High, Critical")
    recommendation: Optional[str] = Field(None, description="Action recommendation")


class DataAnalysisReport(BaseModel):
    """Validated report generated by the LLM."""

    summary: str = Field(..., description="Executive summary")
    key_insights: List[Insight] = Field(..., description="Key findings")
    anomalies: List[str] = Field(default_factory=list, description="Anomalies list")
    overall_score: int = Field(..., ge=1, le=10, description="Score from 1 to 10")
    analysis_timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())


SYSTEM_PROMPT_EXCEL_ANALYZER = """You are a Senior UX Researcher and Data Analyst.

YOUR TASK:
Analyze the provided tabular data from usability testing sessions or qualitative interviews
and generate a comprehensive, structured analysis report.
Return ONLY a valid JSON object matching the schema below.
DO NOT return the schema description. RETURN THE ACTUAL VALUES, not types.
DO NOT wrap your answer in markdown code fences.

REQUIRED FIELDS:
- summary: a STRING (2-3 sentences). NEVER a dict or object.
- key_insights: a LIST of 3 to 5 insight objects.
- anomalies: a LIST of short strings.
- overall_score: an INTEGER between 1 and 10.

Each insight must be an object with these string fields:
- category
- finding
- evidence
- severity (Low, Medium, High, or Critical)
- recommendation

HALLUCINATION PREVENTION:
- Base every insight strictly on the data provided.
- Do not invent numbers or quotes.
- Write insights in the same language as the input data (Portuguese if the data is in Portuguese).

CORRECT EXAMPLE OUTPUT (copy the structure, not the content):
{
  "summary": "Os participantes concluiram a maioria das tarefas, porem relatam baixa confianca ao lidar com rotinas criticas.",
  "key_insights": [
    {
      "category": "Confianca",
      "finding": "Usuarios sentem inseguranca em rotinas criticas.",
      "evidence": "4 de 8 participantes mencionaram receio de automatizar rotinas core.",
      "severity": "High",
      "recommendation": "Adicionar indicadores de risco e checagem extra para rotinas criticas."
    }
  ],
  "anomalies": ["Dois participantes relataram alta satisfacao mesmo com dificuldades de rastreabilidade."],
  "overall_score": 6
}

CRITICAL: Return ONLY a single valid JSON object with REAL values. No markdown. No extra text.
If the data is qualitative (interview text), still return the same JSON structure summarizing the main themes."""

REPORT_JSON_SCHEMA: Dict[str, Any] = {
    "type": "object",
    "properties": {
        "summary": {"type": "string"},
        "key_insights": {
            "type": "array",
            "minItems": 3,
            "maxItems": 5,
            "items": {
                "type": "object",
                "properties": {
                    "category": {"type": "string"},
                    "finding": {"type": "string"},
                    "evidence": {"type": "string"},
                    "severity": {"type": "string", "enum": ["Low", "Medium", "High", "Critical"]},
                    "recommendation": {"type": "string"},
                },
                "required": ["category", "finding", "evidence", "severity", "recommendation"],
            },
        },
        "anomalies": {"type": "array", "items": {"type": "string"}},
        "overall_score": {"type": "integer", "minimum": 1, "maximum": 10},
    },
    "required": ["summary", "key_insights", "anomalies", "overall_score"],
}


class UXExcelAnalyzer:
    """Engine for analyzing structured UX data from Excel using local LLM."""

    def __init__(self, model_name: str = "qwen3:4b", ollama_host: str = "http://localhost:11434"):
        self.model_name = model_name
        self.ollama_host = ollama_host
        self.client = None

        if ollama is None:
            logger.warning("Ollama not installed. Install with: pip install ollama")
            return

        try:
            self.client = ollama.Client(host=ollama_host)
            logger.info("Connected to Ollama at %s", ollama_host)
        except Exception as exc:
            logger.error("Failed to connect to Ollama: %s", exc)

    def load_excel(self, filepath: str, sheet_name: int | str = 0) -> pd.DataFrame:
        """Load and minimally clean an Excel sheet."""
        logger.info("Loading data from %s", filepath)
        df = pd.read_excel(filepath, sheet_name=sheet_name)
        df = df.dropna(how="all")
        df = df.dropna(axis=1, how="all")
        logger.info("Loaded %s rows and %s columns", len(df), len(df.columns))
        return df

    def _prepare_data_for_llm(
        self,
        df: pd.DataFrame,
        max_rows: int = 100,
        max_cell_chars: int = 200,
        max_columns: int = 12,
        max_prompt_chars: int = 12000,
    ) -> str:
        """Build compact context with summary stats and markdown table.

        Long text cells are truncated to *max_cell_chars* to keep the prompt
        within the model context window, which is critical for qualitative
        interview spreadsheets.
        """
        df = self._sanitize_for_analysis(df)

        summary_stats: List[str] = [
            "--- DATA SUMMARY STATISTICS ---",
            f"Total Records: {len(df)}",
            f"Columns: {', '.join(df.columns[:30])}",
        ]

        numeric_cols = df.select_dtypes(include=[np.number]).columns
        if len(numeric_cols) > 0:
            summary_stats.append("\nNumeric Metrics Averages:")
            for col in numeric_cols:
                summary_stats.append(
                    f"- {col}: Mean={df[col].mean():.2f}, Min={df[col].min()}, Max={df[col].max()}"
                )

        cat_cols = df.select_dtypes(include=["object", "category", "bool"]).columns
        if len(cat_cols) > 0:
            summary_stats.append("\nCategorical Distributions:")
            for col in cat_cols:
                if df[col].nunique(dropna=True) <= 10:
                    counts = df[col].value_counts(normalize=True, dropna=True) * 100
                    dist_str = ", ".join([f"{k}: {v:.1f}%" for k, v in counts.head(10).items()])
                    summary_stats.append(f"- {col}: {dist_str}")

        raw_data: List[str] = ["\n--- RAW DATA SAMPLE ---"]
        sample_df = df.head(max_rows) if len(df) > max_rows else df.copy()
        if len(df) > max_rows:
            raw_data.append(f"(Showing first {max_rows} rows out of {len(df)})")

        if len(sample_df.columns) > max_columns:
            kept_cols = sample_df.columns[:max_columns].tolist()
            raw_data.append(
                f"(Showing first {max_columns} columns out of {len(df.columns)} to preserve context window)"
            )
            raw_data.append("\n--- COMPACT FIELD COVERAGE FOR OMITTED COLUMNS ---")
            omitted_cols = sample_df.columns[max_columns:].tolist()
            for col in omitted_cols[:30]:
                values = df[col].dropna().astype(str).map(str.strip)
                values = values[~values.str.lower().isin({"", "nan", "none", "null", "n/a", "na"})]
                examples = [
                    (value[:90] + "...") if len(value) > 90 else value
                    for value in values.head(2).tolist()
                ]
                example_text = " | ".join(examples) if examples else "No valid responses"
                raw_data.append(f"- {col}: {len(values)} responses. Examples: {example_text}")
            if len(omitted_cols) > 30:
                raw_data.append(f"- ... {len(omitted_cols) - 30} additional columns omitted from compact coverage.")
            sample_df = sample_df[kept_cols].copy()

        for col in sample_df.columns:
            if sample_df[col].dtype == object:
                sample_df[col] = sample_df[col].apply(
                    lambda v: (str(v)[:max_cell_chars] + "...") if pd.notna(v) and len(str(v)) > max_cell_chars else v
                )
                sample_df[col] = sample_df[col].fillna("")

        raw_data.append(sample_df.to_csv(index=False))
        payload = "\n".join(summary_stats) + "\n" + "\n".join(raw_data)
        if len(payload) > max_prompt_chars:
            payload = payload[:max_prompt_chars] + "\n\n[TRUNCATED TO FIT CONTEXT WINDOW]"
        return payload

    @staticmethod
    def _sanitize_for_analysis(df: pd.DataFrame) -> pd.DataFrame:
        cleaned = df.copy()
        null_tokens = {"", "nan", "none", "null", "n/a", "na"}

        object_cols = cleaned.select_dtypes(include=["object", "string"]).columns
        for col in object_cols:
            cleaned[col] = cleaned[col].apply(lambda v: str(v).strip() if pd.notna(v) else v)
            cleaned[col] = cleaned[col].apply(
                lambda v: pd.NA
                if pd.notna(v) and str(v).strip().lower() in null_tokens
                else v
            )

        cleaned = cleaned.dropna(axis=0, how="all")
        cleaned = cleaned.dropna(axis=1, how="all")
        return cleaned

    @staticmethod
    def _get_response_text(response: Any) -> str:
        """Read Ollama responses across dict-like and typed client versions."""
        if isinstance(response, dict):
            return str(response.get("response", "")).strip()
        return str(getattr(response, "response", "")).strip()

    @staticmethod
    def _strip_reasoning_blocks(text: str) -> str:
        text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL | re.IGNORECASE)
        text = re.sub(r"```(?:json)?\s*", "", text, flags=re.IGNORECASE)
        text = text.replace("```", "")
        return text.strip()

    @staticmethod
    def _extract_json_object(text: str) -> Dict[str, Any]:
        """Extract the first balanced JSON object from a possibly noisy response."""
        cleaned = UXExcelAnalyzer._strip_reasoning_blocks(text)
        if not cleaned:
            raise ValueError("LLM returned an empty response.")

        start = cleaned.find("{")
        if start == -1:
            raise ValueError(f"LLM response did not contain a JSON object: {cleaned[:180]}")

        depth = 0
        in_string = False
        escaped = False
        for idx, char in enumerate(cleaned[start:], start=start):
            if escaped:
                escaped = False
                continue
            if char == "\\":
                escaped = True
                continue
            if char == '"':
                in_string = not in_string
                continue
            if in_string:
                continue
            if char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
                if depth == 0:
                    return json.loads(cleaned[start : idx + 1])

        raise ValueError(f"LLM response contained incomplete JSON: {cleaned[:180]}")

    def analyze_data(self, df: pd.DataFrame, context_info: str = "") -> Optional[DataAnalysisReport]:
        """Analyze DataFrame with local LLM and validate with Pydantic."""
        if not self.client:
            logger.error("Ollama client not initialized.")
            return None

        clean_df = self._sanitize_for_analysis(df)
        long_text_cols = 0
        for col in clean_df.select_dtypes(include=["object", "string"]).columns:
            avg_len = clean_df[col].dropna().astype(str).str.len().mean() if len(clean_df[col].dropna()) > 0 else 0
            if avg_len and avg_len > 80:
                long_text_cols += 1

        is_qualitative = long_text_cols > 3 or len(clean_df.columns) > 15
        max_rows = 8 if is_qualitative else 60
        max_columns = 10 if is_qualitative else 20
        data_str = self._prepare_data_for_llm(
            clean_df,
            max_rows=max_rows,
            max_cell_chars=120,
            max_columns=max_columns,
            max_prompt_chars=10000 if is_qualitative else 14000,
        )
        user_message = f"""Analyze the following usability testing data.

Context: {context_info if context_info else "General usability test metrics"}

{data_str}

Generate a concise but evidence-based UX analysis based ONLY on this data.
Prefer 3 strong insights over broad generic statements.
Each evidence field must cite a column name, a count, a percentage, or a concrete value from the supplied data.
Return ONLY the JSON object."""

        attempt_prompts = [user_message]
        retry_message = (
            user_message
            + "\n\nYour previous answer was invalid. You MUST return ONLY a JSON object with these exact keys: "
            "summary (string), key_insights (list of objects), anomalies (list of strings), overall_score (integer 1-10). "
            "Use simple strings. DO NOT return markdown, reasoning, field types, or descriptions."
        )
        attempt_prompts.append(retry_message)

        last_error: Optional[Exception] = None
        for attempt, prompt in enumerate(attempt_prompts, start=1):
            try:
                logger.info("Sending data to LLM for analysis (attempt %s)...", attempt)
                response: Dict[str, Any] = self.client.generate(
                    model=self.model_name,
                    prompt=prompt,
                    system=SYSTEM_PROMPT_EXCEL_ANALYZER,
                    stream=False,
                    think=False,
                    format=REPORT_JSON_SCHEMA,
                    options={
                        "temperature": 0.0 if attempt > 1 else 0.1,
                        "top_p": 0.8,
                        "num_ctx": 8192,
                        "num_predict": 1800,
                    },
                )
                response_text = self._get_response_text(response)
                json_data = self._extract_json_object(response_text)
                json_data = self._normalize_llm_output(json_data)
                report = DataAnalysisReport(**json_data)
                logger.info("Analysis report generated successfully")
                return report
            except Exception as exc:
                last_error = exc
                logger.warning("Attempt %s failed: %s", attempt, exc)

        logger.error("Analysis failed after retries: %s", last_error)
        return self._build_fallback_report(clean_df, context_info, last_error)

    @staticmethod
    def _normalize_llm_output(data: Dict[str, Any]) -> Dict[str, Any]:
        """Fix common LLM output deviations before Pydantic validation."""
        if isinstance(data.get("summary"), dict):
            data["summary"] = json.dumps(data["summary"], ensure_ascii=False)

        if isinstance(data.get("key_insights"), dict):
            data["key_insights"] = [data["key_insights"]]

        if isinstance(data.get("key_insights"), list):
            data["key_insights"] = [
                insight for insight in data["key_insights"] if isinstance(insight, dict)
            ]
            for insight in data["key_insights"]:
                if isinstance(insight, dict):
                    # Common alternative output from local models.
                    if "insight" in insight and "finding" not in insight:
                        insight["finding"] = str(insight.get("insight"))
                    if "source" in insight and "evidence" not in insight:
                        insight["evidence"] = f"Source: {insight.get('source')}"
                    if "category" not in insight:
                        insight["category"] = "General"
                    if "severity" not in insight:
                        insight["severity"] = "Medium"
                    if "recommendation" not in insight:
                        insight["recommendation"] = "Review this finding with the UX team."
                    for field in ("category", "finding", "evidence", "severity", "recommendation"):
                        if isinstance(insight.get(field), dict):
                            insight[field] = json.dumps(insight[field], ensure_ascii=False)
                        elif insight.get(field) is None:
                            insight[field] = ""
                        else:
                            insight[field] = str(insight[field]).strip()
                    severity = insight.get("severity", "").lower()
                    severity_map = {
                        "low": "Low",
                        "medium": "Medium",
                        "moderate": "Medium",
                        "high": "High",
                        "critical": "Critical",
                        "baixo": "Low",
                        "media": "Medium",
                        "médio": "Medium",
                        "alta": "High",
                        "alto": "High",
                        "critico": "Critical",
                        "crítico": "Critical",
                    }
                    insight["severity"] = severity_map.get(severity, "Medium")

        if isinstance(data.get("anomalies"), str):
            data["anomalies"] = [data["anomalies"]]
        elif not isinstance(data.get("anomalies"), list):
            data["anomalies"] = []
        else:
            data["anomalies"] = [str(item) for item in data["anomalies"] if item is not None]

        score = data.get("overall_score")
        if isinstance(score, str):
            match = re.search(r"(\d+)", score)
            data["overall_score"] = int(match.group(1)) if match else 5
        if isinstance(score, float):
            data["overall_score"] = int(round(score))
        if data.get("overall_score") is None:
            data["overall_score"] = 5
        try:
            data["overall_score"] = max(1, min(10, int(data["overall_score"])))
        except (TypeError, ValueError):
            data["overall_score"] = 5
        if not data.get("key_insights"):
            data["key_insights"] = [
                {
                    "category": "General",
                    "finding": "The model did not return structured insights in the expected format.",
                    "evidence": "Fallback generated by validator.",
                    "severity": "Medium",
                    "recommendation": "Try analyzing a smaller sample or provide additional context.",
                }
            ]
        if "summary" not in data or not isinstance(data.get("summary"), str):
            data["summary"] = "Structured analysis was generated with fallback normalization."

        return data

    @staticmethod
    def _build_fallback_report(
        df: pd.DataFrame,
        context_info: str,
        error: Optional[Exception] = None,
    ) -> DataAnalysisReport:
        """Create a safe local report when LLM output is invalid."""
        rows, cols = len(df), len(df.columns)
        missing_pct = float(df.isna().sum().sum() / (rows * cols) * 100) if rows and cols else 0.0
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        text_cols = df.select_dtypes(include=["object", "string", "category", "bool"]).columns.tolist()

        insights: List[Insight] = []

        if numeric_cols:
            scored_cols = []
            for col in numeric_cols:
                values = df[col].dropna()
                if values.empty:
                    continue
                scored_cols.append((col, float(values.mean()), values.min(), values.max()))
            if scored_cols:
                col, mean, min_value, max_value = sorted(scored_cols, key=lambda item: item[1])[0]
                insights.append(
                    Insight(
                        category="Quantitative signal",
                        finding=f"The lowest average numeric metric is '{col}', which may indicate the main friction area.",
                        evidence=f"{col}: mean={mean:.2f}, min={min_value}, max={max_value}.",
                        severity="High" if mean <= 3 else "Medium",
                        recommendation=f"Review rows where '{col}' is below the average and compare them with participant comments.",
                    )
                )

        for col in text_cols[:8]:
            values = df[col].dropna().astype(str).map(str.strip)
            values = values[~values.str.lower().isin({"", "nan", "none", "null", "n/a", "na"})]
            if values.empty:
                continue
            counts = values.value_counts()
            top_value = counts.index[0]
            top_count = int(counts.iloc[0])
            if top_count >= 2 and counts.size <= 12:
                pct = top_count / len(values) * 100
                insights.append(
                    Insight(
                        category="Categorical pattern",
                        finding=f"The most frequent value in '{col}' is '{top_value}'.",
                        evidence=f"{top_count} of {len(values)} valid responses ({pct:.1f}%).",
                        severity="Medium" if pct >= 50 else "Low",
                        recommendation=f"Use '{col}' as a segmentation field when reviewing the detailed responses.",
                    )
                )
                break

        insights.append(
            Insight(
                category="Data Quality",
                finding="Local fallback report was used because LLM output was not schema-compliant.",
                evidence=f"Rows={rows}, Cols={cols}, Missing={missing_pct:.1f}%",
                severity="Medium",
                recommendation="Use a smaller sample, add concise context, or retry after freeing system memory.",
            )
        )

        while len(insights) < 3:
            insights.append(
                Insight(
                    category="Dataset Profile",
                    finding="Dataset appears to contain interview-style text fields."
                    if len(numeric_cols) <= 2
                    else "Dataset contains mixed quantitative and qualitative fields.",
                    evidence=f"Numeric columns detected: {len(numeric_cols)}; text/categorical columns detected: {len(text_cols)}.",
                    severity="Low",
                    recommendation="Use the Visualizations tab to cross-check these AI findings with deterministic summaries.",
                )
            )

        summary = (
            f"Fallback analysis generated for {rows} records and {cols} columns."
            f" Context: {context_info or 'General usability data'}."
        )
        anomalies = []
        if missing_pct > 30:
            anomalies.append(f"High missing data ratio detected: {missing_pct:.1f}%.")
        if error:
            anomalies.append(f"LLM schema validation error: {str(error)[:180]}")

        return DataAnalysisReport(
            summary=summary,
            key_insights=insights,
            anomalies=anomalies,
            overall_score=5,
        )

    def export_report(self, report: DataAnalysisReport, filepath: str) -> None:
        """Export analysis report to markdown."""
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("# UX Data Analysis Report\n\n")
            f.write(f"*Generated on: {report.analysis_timestamp}*\n\n")
            f.write("## Executive Summary\n")
            f.write(f"{report.summary}\n\n")
            f.write(f"**Overall Usability Score:** {report.overall_score}/10\n\n")
            f.write("## Key Insights\n\n")

            for i, insight in enumerate(report.key_insights, 1):
                f.write(f"### {i}. {insight.category}\n")
                f.write(f"- **Finding:** {insight.finding}\n")
                f.write(f"- **Evidence:** {insight.evidence}\n")
                f.write(f"- **Severity:** {insight.severity}\n")
                if insight.recommendation:
                    f.write(f"- **Recommendation:** {insight.recommendation}\n")
                f.write("\n")

            if report.anomalies:
                f.write("## Anomalies and Outliers\n\n")
                for anomaly in report.anomalies:
                    f.write(f"- {anomaly}\n")

        logger.info("Report exported to %s", filepath)


def create_sample_excel(filepath: str) -> pd.DataFrame:
    """Create simple sample Excel file for local testing."""
    data = {
        "Session_ID": [f"S{i:03d}" for i in range(1, 21)],
        "Task_Name": ["Login"] * 10 + ["Checkout"] * 10,
        "Success": [
            True,
            True,
            False,
            True,
            True,
            True,
            False,
            True,
            True,
            True,
            True,
            False,
            False,
            True,
            False,
            True,
            True,
            False,
            True,
            True,
        ],
        "Completion_Time_Sec": [
            45,
            50,
            120,
            40,
            55,
            48,
            180,
            42,
            51,
            47,
            180,
            350,
            420,
            195,
            380,
            170,
            210,
            400,
            185,
            190,
        ],
        "Error_Count": [0, 0, 2, 0, 1, 0, 3, 0, 0, 0, 1, 4, 5, 1, 4, 0, 2, 3, 1, 0],
        "Satisfaction_Rating": [5, 4, 2, 5, 4, 5, 1, 5, 4, 5, 4, 1, 1, 3, 2, 4, 3, 1, 4, 4],
        "User_Age": [25, 34, 55, 28, 42, 31, 62, 24, 38, 29, 25, 55, 62, 34, 42, 28, 31, 38, 24, 29],
        "Experience_Level": [
            "Expert",
            "Intermediate",
            "Novice",
            "Expert",
            "Intermediate",
            "Expert",
            "Novice",
            "Expert",
            "Intermediate",
            "Expert",
            "Expert",
            "Novice",
            "Novice",
            "Intermediate",
            "Intermediate",
            "Expert",
            "Expert",
            "Intermediate",
            "Expert",
            "Expert",
        ],
    }
    df = pd.DataFrame(data)
    df.to_excel(filepath, index=False)
    logger.info("Created sample Excel file at %s", filepath)
    return df


def main() -> None:
    base_dir = Path(__file__).resolve().parent
    excel_path = str(base_dir / "sample_ux_data.xlsx")
    create_sample_excel(excel_path)

    analyzer = UXExcelAnalyzer(model_name="qwen3:4b")
    df = analyzer.load_excel(excel_path)
    report = analyzer.analyze_data(
        df,
        context_info="A/B test comparing new Login and Checkout flows.",
    )

    if report:
        report_path = str(base_dir / "ux_analysis_report.md")
        analyzer.export_report(report, report_path)
        print(f"OVERALL SCORE: {report.overall_score}/10")
        print(report.summary)
    else:
        print("Analysis failed. Check Ollama connection.")


if __name__ == "__main__":
    main()
